import './globals.css'

import { Work_Sans } from 'next/font/google';

const workSans = Work_Sans ({subsets: ['latin']})

export const metadata = {
  icon: '/src/app/icon.png',
  title: 'FAQ Accordion',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <link
        rel="icon"
        href="/icon?<generated>"
        type="image/<generated>"
        sizes="<generated>"
      />

      <body className={workSans.className}>{children}</body>
    </html>
  )
}
